[build]
builder = "maven"
buildCommand = "mvn clean package -DskipTests"

[deploy]
startCommand = "java -jar target/Gestion_des_Rendezvous-0.0.1-SNAPSHOT.jar"
healthcheckPath = "/"
healthcheckTimeout = 100